version: 0.2

env:
  variables:
    githubOwner: $GITHUBOWNER

phases:
  install:
    commands:
      - pip install --upgrade awscli
      - pip install requests -t bin
  # pre_build:
  #   commands:
  #     - echo Running python unit tests
  #     - cd SAM && python -m unittest tests
  #     - cd ..
  build:
    commands:
      - echo Build started on `date`
      - echo $BUILD_OUTPUT_BUCKET
      - echo $GITHUBOWNER
      - sh aws-foundation/foundation/fetch-parameters.sh
      - cat parameters.json
      - cp -R bin/* .
      - ls
      - aws cloudformation package --template-file bin/cfn-sam.yml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file NewSamTemplate.yaml
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml
    - parameters.json
  discard-paths: yes